name: Build

on: [workflow_dispatch]

jobs:
  Build:
    name: ${{ matrix.platform.name }}
    runs-on: ${{ matrix.platform.os }}
    strategy:
      matrix:
        platform:
        - { name: Windows, os: windows-latest }
    steps:
    - name: Setup Linux dependencies
      if: runner.os == 'Linux'
      run: |
        sudo apt-get update
        sudo apt-get install cmake ninja-build libgl1-mesa-dev libglu1-mesa-dev
    - name: Get sdl12-compat sources
      uses: actions/checkout@v2
    - name: Get SDL2 headers
      uses: actions/checkout@v2
      with:
        repository: libsdl-org/SDL
        ref: release-2.0.18
        path: SDL2
    - name: Configure CMake
      run: cmake -DSDL2_INCLUDE_DIR="${{ github.workspace }}/SDL2/include" -DCMAKE_BUILD_TYPE=Release . -B build ${{ matrix.platform.flags }}
    - name: Build
      run: cmake --build build/
      
  
    # Downloads .zip from libsdl-org repo
    - name: Download SDL2 zip
      run: curl -L -o SDL2.zip https://github.com/libsdl-org/SDL/releases/download/release-2.26.2/SDL2-2.26.2-win32-x64.zip

    # unzips .zip
    - name: Unzip SDL2 zip
      run: 7z x SDL2.zip

    # Moves SDL2.dll to debug subdir
    - name: Move SDL.dll
      run: move D:\a\df-sdl12-compat\df-sdl12-compat\build\debug\SDL.dll D:\a\df-sdl12-compat\DF-SDL12-COMPAT\SDL.dll

    - name: Show file structure
      run: tree "D:"/F
      
    - name: Automatic Releases
      uses: marvinpinto/action-automatic-releases@v1.2.1
      with:
        repo_token: "${{ secrets.GITHUB_TOKEN }}"
        automatic_release_tag: "latest"
        prerelease: true
        draft: true
        title: "SDL1.2-compat release"
        files: |
          LICENSE.txt
          SDL.dll
          SDL2.dll
